config/routes.rb
Rails.application.routes.draw do

devise_for :users

resources :tickets
resource :search, only: [:new, :show, :create]
  
namespace :admin do
  resources :railway_stations do
    patch :update_position, on: :member
    patch :update_arrive_time, on: :member
    patch :update_departure_time, on: :member
  end

  resources :routes
  
  resources :tickets

  resources :trains do
    resources :carriages, shallow: true
  end

  get 'welcome/index'
end

  get 'welcome/index'
  

  root 'searches#show'

end

app/models/railway_station.rb
class RailwayStation < ActiveRecord::Base
  has_many :trains, foreign_key: :current_station_id
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  validates :title, presence: true

  scope :ordered, -> { select('railway_stations.*, railway_stations_routes.position').joins(:railway_stations_routes).order("railway_stations_routes.position").uniq }

  def update_position(route, position)
    station_route = station_route(route)
    station_route.update(position: position) if station_route
  end

  def position_in(route)
    station_route(route).try(:position)
  end

  def update_arrive(route, arrive_time)
    station_route = station_route(route)
    station_route.update(arrive_time: arrive_time) if station_route
  end

  def arrive(route)
    station_route(route).try(:arrive_time)
  end

  def update_departure(route, departure_time)
    station_route = station_route(route)
    station_route.update(departure_time: departure_time) if station_route
  end

  def departure(route)
    station_route(route).try(:departure_time)
  end

  protected

    def station_route(route)
      @station_route ||= railway_stations_routes.where(route: route).first
    end
end

app/controllers/admin/railway_stations_controller.rb
class Admin::RailwayStationsController < Admin::BaseController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy, :update_position, :update_arrive_time, :update_departure_time]

  def index
    @railway_stations = RailwayStation.all
  end

  def show
  end

  def new
    @railway_station = RailwayStation.new
  end

  def edit
  end

  def create
    @railway_station = RailwayStation.new(railway_station_params)

    respond_to do |format|
      if @railway_station.save
        format.html { redirect_to [:admin, @railway_station], notice: 'Railway station was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @railway_station.update(railway_station_params)
        format.html { redirect_to admin_railway_stations_path, notice: 'Railway station was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @railway_station.destroy
    respond_to do |format|
      format.html { redirect_to admin_railway_stations_url, notice: 'Railway station was successfully destroyed.' }
    end
  end

  def update_position
    @route = Route.find(params[:route_id])
    @railway_station.update_position(@route, params[:position])
    redirect_to [:admin, @route]
  end

  def update_arrive_time
    @route = Route.find(params[:route_id])
    @railway_station.update_arrive(@route, params[:arrive_time])
    redirect_to [:admin, @route]
  end

  def update_departure_time
    @route = Route.find(params[:route_id])
    @railway_station.update_departure(@route, params[:departure_time])
    redirect_to [:admin, @route]
  end

  private
    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    def railway_station_params
      params.require(:railway_station).permit(:title, :number)
    end
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/views/admin/railway_stations/_form.html.erb
<% hidden = false unless local_assigns[:hidden] %>

<%= form_for [:admin, station], html: { style: "display: #{hidden ? 'none' : 'block'}" } do |f| %>

  <%= render 'common/errors', resource: station %>

  <div class="field">
    <%= f.text_field :title, class: "form-control", placeholder: "Название станции"  %>
  </div>

  <div class="actions">
    <%= f.submit t('.submit', action: station.new_record? ? 'Создать' : 'Изменить'), class: "btn btn-default"%>
  </div>
  
<% end %>

app/views/admin/railway_stations/_railway_station.html.erb
<tr>
  <td>
    <div id="railway_station_title_<%= railway_station.id %>">
      <%= railway_station.title %>
    </div>
    <%= render 'form', station: railway_station, hidden: true %>
  </td>
  <td><%= link_to 'Показать', admin_railway_station_path(railway_station) %></td>
  <td><%= link_to 'Редактировать', '', class: 'edit_station', data: { station_id: railway_station.id } %></td>
  <td><%= link_to 'Удалить', admin_railway_station_path(railway_station), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/railway_stations/edit.html.erb
<h1>Редактирование станции</h1>

<div class="row">
  <div class="col-md-3">

		<%= render 'form', station: @railway_station %>

		<%= link_to 'Показать', [:admin, @railway_station] %> /
		<%= link_to 'Назад', admin_railway_stations_path %>	
	</div>
</div>

app/views/admin/railway_stations/index.html.erb
<h1>Список станций</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Название</th>
    </tr>
  </thead>

  <tbody>
    <%= render @railway_stations %>
  </tbody>
</table>

<br>

<%= link_to 'Создать', new_admin_railway_station_path %>

app/views/admin/railway_stations/new.html.erb
<h1> <%= t('.title') %> </h1>

<div class="row">
  <div class="col-md-3">

    <%= render 'form', station: @railway_station %>

    <%= link_to t('common.back'), admin_railway_stations_path %> 
    
  </div>
</div>

app/views/admin/railway_stations/show.html.erb
<p>
  <strong>Название:</strong>
  <%= @railway_station.title %>
</p>

<p>
	<% if @railway_station.routes.empty? %>
	  <p>Станция не входит ни в один маршрут</p>
	<% else %>
	  <p> Станция входит в следующие маршруты:</p>
	  <ul>
	    <% @railway_station.routes.each do |route| %>
	      <li><%= route.title %></li>
	     <% end %>
	  </ul>
	<% end %>
</p>

<%= link_to 'Редактирование', edit_admin_railway_station_path(@railway_station) %> /
<%= link_to 'Назад', admin_railway_stations_path %> /
<%= link_to 'Главная', welcome_index_path %>