config/routes.rb
Rails.application.routes.draw do

devise_for :users

resources :tickets
resource :search, only: [:new, :show, :create]
  
namespace :admin do
  resources :railway_stations do
    patch :update_position, on: :member
    patch :update_arrive_time, on: :member
    patch :update_departure_time, on: :member
  end

  resources :routes
  
  resources :tickets

  resources :trains do
    resources :carriages, shallow: true
  end

  get 'welcome/index'
end

  get 'welcome/index'
  

  root 'searches#show'

end

app/models/carriage.rb
class Carriage < ActiveRecord::Base
  TYPES = %w(ComfortCarriage EconomyCarriage SitCarriage SvCarriage)

  belongs_to :train
  
  validates :type_car, presence: true, inclusion: { in: TYPES }
  validates :number, uniqueness: { scope: :train_id }
  
  before_validation :set_number

  private
    def set_number
      number = train.carriages.maximum(:number)
      self.number = number.nil? ? 1 : number + 1
    end
end

app/models/comfort_carriage.rb
class ComfortCarriage < Carriage
  validates :up_places, :lower_places, presence: true
end

app/models/economy_carriage.rb
class EconomyCarriage < Carriage
  validates :up_places, :lower_places, :side_up_places, :side_lower_places, presence: true
end

app/models/railway_station.rb
class RailwayStation < ActiveRecord::Base
  has_many :trains, foreign_key: :current_station_id
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  validates :title, presence: true

  scope :ordered, -> { select('railway_stations.*, railway_stations_routes.position').joins(:railway_stations_routes).order("railway_stations_routes.position").uniq }

  def update_position(route, position)
    station_route = station_route(route)
    station_route.update(position: position) if station_route
  end

  def position_in(route)
    station_route(route).try(:position)
  end

  def update_arrive(route, arrive_time)
    station_route = station_route(route)
    station_route.update(arrive_time: arrive_time) if station_route
  end

  def arrive(route)
    station_route(route).try(:arrive_time)
  end

  def update_departure(route, departure_time)
    station_route = station_route(route)
    station_route.update(departure_time: departure_time) if station_route
  end

  def departure(route)
    station_route(route).try(:departure_time)
  end

  protected

    def station_route(route)
      @station_route ||= railway_stations_routes.where(route: route).first
    end
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ActiveRecord::Base
  belongs_to :railway_station
  belongs_to :route

  validates :railway_station_id, uniqueness: { scope: :route_id }
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :trains
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

  validates :title, presence: true
  validate :stations_count

  before_validation :set_name

  private    
    def set_name
      self.title = "#{railway_stations.first.title} - #{railway_stations.last.title}"
    end

    def stations_count
      if railway_stations.size < 2
        errors.add(:base, "Route should contain at least 2 stations")
      end
    end
end

app/models/search.rb
class Search
  def self.search_trains(primary_station, terminal_station)
    if primary_station != terminal_station
      routes = Route.joins(:railway_stations).where(railway_stations: { id: primary_station }) &
               Route.joins(:railway_stations).where(railway_stations: { id: terminal_station })
      Train.joins(:route).where(route: routes)
    end
  end
end

app/models/sit_carriage.rb
class SitCarriage < Carriage
  validates :sit_places, presence: true
end

app/models/sv_carriage.rb
class SvCarriage < ActiveRecord::base
  validates :lower_places, presence: true
end

app/models/sv_carriages.rb
class SvCarriage < Carriage
  validates :lower_places, presence: true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user 
  belongs_to :train
  belongs_to :primary_station, class_name: 'RailwayStation', foreign_key: :primary_station_id
  belongs_to :terminal_station, class_name: 'RailwayStation', foreign_key: :terminal_station_id

  validates :number, presence: true

  after_create :send_notification
  after_destroy :send_delete_notification

  private
  def send_notification
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end

  def send_delete_notification
    TicketsMailer.delete_ticket(self.user, self).deliver_now
  end
end

app/models/train.rb
class Train < ActiveRecord::Base
  has_many :tickets
  has_many :carriages
  
  belongs_to :route
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id

  validates :number, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
  has_many :tickets
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @route = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def edit
  end

  def create
    @route = Route.new(route_params)
 
    if @route.save
      redirect_to [:admin, @route]
    else
      render 'new'
    end
  end

  def update 
    if @route.update(route_params)
      redirect_to admin_routes_path
    else
      render 'edit'
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end

  private
    def set_route
      @route = Route.find(params[:id])
    end

    def route_params
      params.require(:route).permit(:title, :route_id, railway_station_ids: [], train_ids: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(current_user)
    current_user.admin? ? admin_welcome_index_path : root_path
  end

  # def after_sign_out_path_for(resource)
  #   # return the path based on resource
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
  end

  def new

  end

  def create
    @trains = Search.search_trains(params[:primary_station_id], params[:terminal_station_id])
    render :show
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = current_user.tickets
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def edit
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)

    if @ticket.save
      redirect_to @ticket, notice: "Билет #{@ticket.number} куплен"
    else
      render 'new'
    end
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket
    else
      render 'edit'
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_path
  end

  private
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    def ticket_params
      params.require(:ticket).permit(:number, :fio, :passport, :user_id, :train_id, :primary_station_id, :terminal_station_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.all
  end

  def show  
  end

  def new
    @user = User.new
  end

  def edit  
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:title)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/routes/_form.html.erb
<% hidden = false unless local_assigns[:hidden] %>

<%= form_for [:admin, route], html: { style: "display: #{hidden ? 'none' : 'block'}" } do |f| %>

  <%= render 'common/errors', resource: route %>

  <div class="field">
    <%= f.text_field :title, class: "form-control", placeholder: "Название маршрута" %>
  </div>

  <div class="field">
    <%= f.label :railway_station_ids %>
    <%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true } %>
  </div>
 
  <div class="field">
    <%= f.submit t('.submit', action: route.new_record? ? 'Создать' : 'Изменить'), class: "btn btn-default"%>
  </div>
<% end %>

app/views/admin/routes/edit.html.erb
<h1> <%= t('.title') %> </h1>

<div class="row">
  <div class="col-md-3">
 
    <%= render 'form', route: @route %>
     
    <%= link_to 'Назад', admin_routes_path %>

  </div>
</div>

app/views/admin/routes/index.html.erb
<h1>Список маршрутов</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Название</th>
    </tr>
  </thead>
 
  <tbody>
    <% @route.each do |route| %>
      <tr>
        <td>
          <div id="route_title_<%= route.id %>">
            <%= route.title %>
          </div>
          <%= render 'form', route: route, hidden: true %>
        </td>
        <td><%= link_to 'Показать', [:admin, route] %></td>
        <td><%= link_to 'Редактировать', '', class: 'edit_route', data: { route_id: route.id } %></td>
        <td><%= link_to 'Удалить', [:admin, route],
                method: :delete,
                data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Создать', new_admin_route_path %>

app/views/admin/routes/new.html.erb
<h1><%= t('.title') %> </h1>

<div class="row">
  <div class="col-md-3">

    <%= render 'form', route: @route %>

    <%= link_to t('common.back'), admin_routes_path %>

  </div>
</div>

app/views/admin/routes/show.html.erb
<p>
  <strong>Название:</strong>
  <%= @route.title %>
</p>


<p>
  <strong>Станции:</strong>
  <% if @route.railway_stations.empty? %>
      Список пуст
  <% else %>
    <table class="table table-striped table-hover ">
      <thead>
      <tr>
        <td width="100px">Название</td>
        <td>Позиция</td>
        <td>Прибытие</td>
        <td>Отправление</td>
      </tr>
      </thead>

      <tbody>
        <% @route.railway_stations.ordered.each do |st| %>
          <tr>
            <td><%= st.title %></td>

            <td>
              <%= form_tag update_position_admin_railway_station_path(st), method: :patch do %>
                <%= number_field_tag :position, st.position_in(@route) %>
                <%= hidden_field_tag :route_id, @route.id %>
                <%= submit_tag "Изменить" %>
              <% end %>
            </td>

            <td>
              <%= form_tag update_arrive_time_admin_railway_station_path(st), method: :patch do %>   
                <%= time_field_tag :arrive_time, st.arrive(@route).try(:strftime, "%H:%M") %>
                <%= hidden_field_tag :route_id, @route.id %>
                <%= submit_tag "Изменить" %>
              <% end %>
            </td>

            <td>
              <%= form_tag update_departure_time_admin_railway_station_path(st), method: :patch do %>
                <%= time_field_tag :departure_time, st.departure(@route).try(:strftime, "%H:%M") %>
                <%= hidden_field_tag :route_id, @route.id %>
                <%= submit_tag "Изменить" %>
              <% end %>
            </td>

          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</p>

<p>
  <strong>Поезда на маршруте:</strong>
  <% if @route.trains.empty? %>
    <p>Поездов нет</p>
  <% else %>
    <% @route.trains.each do |tr| %>
      <li><%= tr.number %></li>
    <%end%>
  <% end %>
</p>

<%= link_to 'Редактирование', edit_admin_route_path(@route) %> /
<%= link_to 'Назад', admin_routes_path %> /
<%= link_to 'Главная', root_path %>