config/routes.rb
Rails.application.routes.draw do

devise_for :users

resources :tickets
resource :search, only: [:new, :show, :create]
  
namespace :admin do
  resources :railway_stations do
    patch :update_position, on: :member
    patch :update_arrive_time, on: :member
    patch :update_departure_time, on: :member
  end

  resources :routes
  
  resources :tickets

  resources :trains do
    resources :carriages, shallow: true
  end

  get 'welcome/index'
end

  get 'welcome/index'
  

  root 'searches#show'

end

app/models/train.rb
class Train < ActiveRecord::Base
  has_many :tickets
  has_many :carriages
  
  belongs_to :route
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id

  validates :number, presence: true
  
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to [:admin, @train], notice: 'Train was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to admin_trains_path, notice: 'Train was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to admin_trains_url, notice: 'Train was successfully destroyed.' }
    end
  end

  private
    def set_train
      @train = Train.find(params[:id])
    end

    def train_params
      params.require(:train).permit(:number, :route_id, :current_station_id, :is_head)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<% hidden = false unless local_assigns[:hidden] %>

<%= form_for [:admin, train], html: { style: "display: #{hidden ? 'none' : 'block'}" } do |f| %>

  <%= render 'common/errors', resource: train %>

  <div class="field">
    <%= f.number_field :number, class: "form-control", placeholder: "Номер поезда" %>
  </div>
   
  <div class="field">
    <%= f.label :current_station %>  
    <%= f.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="field">
    <%= f.label :route %>
    <%= f.collection_select :route_id, Route.all, :id, :title %>
  </div>
  
  <div class="field">
    <%= f.label :is_head %>
    <%= f.check_box :is_head %>
  </div> 

  <div class="actions">
    <%= f.submit t('.submit', action: train.new_record? ? 'Создать' : 'Изменить'), class: "btn btn-default"%>
  </div>

<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td>
    <div id="train_number_<%= train.id %>">
      <%= train.number %>  
    </div>
    <%= render 'form', train: train, hidden: true %>
    </td>
  <td><%= link_to 'Показать', [:admin, train] %></td>
  <td><%= link_to 'Редактировать', '', class: 'edit_train', data: { train_id: train.id } %></td>
  <td><%= link_to 'Удалить', [:admin, train], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1>Редактирование поезда</h1>

<div class="row">
  <div class="col-md-3">
    
    <%= render 'form', train: @train %>

    <%= link_to 'Показать', [:admin, @train] %> /
    <%= link_to 'Назад', admin_trains_path %> 

  </div>
</div>

app/views/admin/trains/index.html.erb
<h1>Список поездов</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Номер:</th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'Создать', new_admin_train_path %>

app/views/admin/trains/new.html.erb
<h1> <%= t('.title') %> </h1>

<div class="row">
  <div class="col-md-3">

    <%= render 'form', train: @train %>

    <%= link_to t('common.back'), admin_trains_path %>
  
  </div>
</div>

app/views/admin/trains/show.html.erb
<p>
  <strong>Номер:</strong>
  <%= @train.number %>
</p>

<p>
  <strong>На станции:</strong>
  <% if @train.current_station.present? %>
    <%= @train.current_station.title %>
  <% else %>
    Не указано
  <% end %>  
</p>

<p>
  <strong>Маршрут:</strong>
  <% if @train.route.present? %>
    <%= @train.route.title %>
  <% else %>
    Не указан
  <% end %>
</p>

<p>
  <%= link_to "Добавить вагон", new_admin_train_carriage_path(@train) %>
</p>

<p>
  <strong>Вагоны</strong>

  <ul>
    <% if @train.is_head? %>
      <% @train.carriages.order(:number).each do |car| %>      
        <li><%= link_to "Вагон №#{car.number}", [:admin, car] %></li>
      <% end %>
    <% else %>
      <% @train.carriages.order(number: :desc).each do |car| %>
        <li><%= link_to "Вагон №#{car.number}", [:admin, car] %></li>
      <% end %>
    <% end %>
  </ul>
</p>

<%= link_to 'Редактировать', edit_admin_train_path(@train) %> /
<%= link_to 'Назад', admin_trains_path %>